#!/bin/bash

mkdir /tmp/tests 2>/dev/null
export RESULT_FILE="/tmp/tests/B2G_tests.$(date +%Y%m%d%H%M%S)"
export ERR_FILE=${RESULT_FILE}.errors
export RUNTEST="./bin/run_test_case"

# Some required input first ...
printf "\n**************************\n\n"
printf "Some of the tests require your input (if you'd prefer the script reads an input file for this just let me know).\n\n"
ans=""
while [ ! "$ans" ]
do
    printf "Please enter a tel number I can send test sms messages to (you may need to reply to the test sms): "
    read ans
done
echo ""
export TEST_10_NUM=$ans


echo "Making sure you're using the gaiatest suite loaded here (it has some necessary tweaks!) ...."
cd gaia-ui-tests
sudo python setup.py develop > /tmp/gaiatest_install.log 2> /tmp/gaiatest_install.log
cd - > /dev/null 2>/dev/null

# Establsh connection to device.
./bin/connect_device


#
# Now run tests as required.
#
TESTDIR="./smoketests"
$RUNTEST 7 "Add a contact"                          $TESTDIR/test_07.py $RESULT_FILE $ERR_FILE
$RUNTEST 8 "Edit a contact"                         $TESTDIR/test_08.py $RESULT_FILE $ERR_FILE
$RUNTEST 9 "Send SMS from contact"                  $TESTDIR/test_09.py $RESULT_FILE $ERR_FILE
$RUNTEST 10 "Send + receive sms"                    $TESTDIR/test_10.py $RESULT_FILE $ERR_FILE
$RUNTEST 11 "Take picture"                          $TESTDIR/test_11.py $RESULT_FILE $ERR_FILE
$RUNTEST 12 "Take video / check gallery"       	    $TESTDIR/test_12.py $RESULT_FILE $ERR_FILE
$RUNTEST 13 "Take video / check player"       	    $TESTDIR/test_13.py $RESULT_FILE $ERR_FILE

printf "\n\n"
echo "*******************************************************"
printf "\n             RESULT SUMMARY: \n\n"
echo "*******************************************************"
cat $RESULT_FILE
printf "\n*******************************************************\n\n"
printf "(These results are stored in $RESULT_FILE.)\n\n"
