import GLOBAL
frame_locator          = ('css selector', 'iframe[src="app://communications.gaiamobile.org/index.html"]')
view_all_header        = ('xpath', GLOBAL.app_head_specific % 'Contacts')
view_all_contact_xpath = '//*[@data-order="%s"]'
view_all_fb_contacts   = ('class name', "icon-social icon-fb")
settings_button        = ('id', 'settings-button')
settings_header        = ('xpath', GLOBAL.app_head_specific % 'Settings')
#settings_fb_enable     = ('xpath', '//li[@class="fb-item"]')
settings_import_fb     = ('id', 'import-fb') 
add_contact_button     = ('id', 'add-contact-button')
add_contact_header     = ('xpath', GLOBAL.app_head_specific % 'Add contact')
view_details_title     = ('id', 'contact-form-title')
details_back_button    = ('id', 'details-back')

edit_contact_header    = ('xpath', GLOBAL.app_head_specific % 'Edit contact')
edit_update_button     = ('id', 'save-button')
edit_details_button    = ('id', 'edit-contact-button')
done_button            = ('id', 'save-button')

given_name_field       = ('id', 'givenName')
family_name_field      = ('id', 'familyName')
email_field            = ('id', "email_0")
phone_field            = ('id', "number_0")
street_field           = ('id', "streetAddress_0")
zip_code_field         = ('id', "postalCode_0")
city_field             = ('id', 'locality_0')
country_field          = ('id', 'countryName_0')
comment_field          = ('id', 'note_0')
sms_button             = ('id', 'send-sms-button-0')
link_button            = ('id', "link_button") # WARNING: >1 element has this id!
