here_check              = ('id', 'shortcuts-items')
groups                  = ('xpath', "//*[@id='shortcuts-items']//li")
apps                    = ('xpath', "//li[@class='cloud']")
back_btn                = ('id', 'button-clear')
add_app_to_homescreen   = ('id', 'modal-dialog-confirm-ok')
