import GLOBAL
fb_friends_header       = ('xpath', GLOBAL.app_head_specific % 'Facebook Friends')
fb_friends_list         = ('xpath', "//li[@class='block-item']")
fb_link_friends_list    = ('xpath', "//ol[@id='friends-list']//li")
fb_totals               = ('id', 'fb-totals')
#email                   = ("name", "email")
#password                = ("name", "pass")
#login_button            = ("name", "login")
#install_fbowd_button    = ("id", "grant_clicked")
fb_friends_iframe_1     = ("src", "app://communications.gaiamobile.org/contacts/index.html")
fb_friends_iframe_2     = ("id", 'fb-extensions')
fb_friends_select_all   = ('id', 'select-all')
fb_friends_deselect_all = ('id', 'deselect-all')
fb_friends_import       = ('id', 'import-action')
fb_friends_update       = ('id', 'update-action')
