search_query            = ('id', 'search-q')
featured_apps           = ('xpath', ".//*[@id='featured-home']/ul/li/a/canvas")
install_button          = ('css selector', '.button.product.install')
app_details_header      = ('xpath', '//h3')
confirm_install_button  = ('id', 'app-install-install-button')
